### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by cbk914** [rafael-santiago/hefesto#1]
On a Kali 2019.3 Linux System, after a succesful compilation process and installation, when trying to execute hefesto following error appears:

hefesto WARNING: unable to resolve file name "~/toolsets/common/utils/lang/c/dependency_scanner.hsl" 
hefesto WARNING: unable to resolve file name "~/toolsets/common/utils/lang/c/dependency_scanner.hsl" 
hefesto syntax error: Install.hsl: line 30: mktree($bindir); : unknown symbol, statement or call.
hefesto compile error!
hefesto syntax error: Install.hsl: line 75: mktree($dst_root); : unknown symbol, statement or call.
hefesto compile error!
hefesto syntax error: Install.hsl: line 134: mktree(pathfromfilepath($dst_item)); : unknown symbol, statement or call.
hefesto compile error!
hefesto syntax error: Install.hsl: line 174: (isfile($file_item)) : invalid expression.
hefesto compile error!
hefesto: compilation failure with 4 error(s).
2

Hefesto is recognized by the system as installed in /usr/local/bin/hefesto and some directories and files are also installed on /usr/bin. Maybe it's searching for the wrong location, but not sure how to fix it.

Thank you

**Comment by cbk914** [comment]
Selfrespond: Edit the .hsl files done it.

**Comment by cbk914** [comment]
That last one cannot fix, the path is not in the hsl files on install directory.

hefesto WARNING: unable to resolve file name "~/fsutil.hsl" 
hefesto WARNING: unable to resolve file name "~/fsutil.hsl" 
hefesto: script compilation success.
hefesto WARNING: unable to resolve file name "~/fsutil.hsl" 
hefesto syntax error: forge function "clang_c_binary_forge" implementation not found.
hefesto: toolset load failure.

**Comment by rafael-santiago** [comment]
Try to logout and then login again. It should solve the file not found issues. The problem seems to be related to environment variables that were not refreshed yet. You should not edit the hsl file.

**Comment by cbk914** [comment]
OK, solved, thanks!
